### ISSUE TITLE
New Shelter Survey not opening in EB

### ISSUE THREAD

**Issue by epratt5** [afackler/NAPSG-Shelter-System#29]
The New Shelter survey form is not loading in the Experience Builder.

**Comment by epratt5** [comment]
Compatibility issue between S123 & EB. Should be resolved 10/19-10/20.

**Comment by epratt5** [comment]
Resolved by Esri.

**Comment by epratt5** [comment]
I accidentally deleted Current Occupancy.

**Comment by epratt5** [comment]
You have to sign out then back in from the Experience Builder page itself when switching between accounts to make the changes save.
The survey is now corrected.

**Comment by kkay82** [comment]
Still doesn't seem to work for me:

![image](https://user-images.githubusercontent.com/67169954/99083531-e69da780-2582-11eb-8739-79ece87bc655.png)

**Comment by epratt5** [comment]
It's not working for me either. Boo. I think it's still getting hung up when I switch between AGOL accounts. It shouldn't, but I think it is. I'm going to try clearing my cache and cookies, then opening it with the NCR login.

**Comment by epratt5** [comment]
I think I need to contact Esri about this.

**Comment by epratt5** [comment]
I can access the survey outside of Experience Builder.

**Comment by epratt5** [comment]
Talked with Esri support on 11/17/2020. Spoke with Sujay Chirmade. He is going to test the survey in house because from what he sees, all the privileges and settings are correct. There shouldn't even be an issue between organizations because I am an Admin in NAPSG and Scott is the Admin for NCR. It's probably an Experience Builder issue. He'll be in touch with me, hopefully soon.

**Comment by epratt5** [comment]
Seems like making the EB public is the issue. I was able to keep all the other moving parts within the organization, even the survey form, but made EB public. It looks like it's now working. Esri and I will continue to monitor this throughout the week to see if it is just a random day bug, but we're pretty confident the issue should be resolved now.

**Comment by epratt5** [comment]
Esri has closed this case now. If there are any further problems, try refreshing or reopening the Experience Builder. Any further issues are most likely on the EB side of things, as it's a new application and had an update just a few weeks ago.
ESRI Case # 02683018
Tech Support: Sujay, 888-377-4575
